name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install
  
  step-b:
  
    runs-on: ubuntu-latest
    #needs: [build-and-test]
    steps:
      - name: step b
      - run: |
          echo "step b 1"
          echo "step b 2"
      - name: step c
      - run: |
          echo "step b 3"
          echo "step b 4"
  step-c:
  
    runs-on: ubuntu-latest
    needs: [build-and-test, step-b]
    steps:
      - name: step c
      - run: |
          echo "step c 1"
          echo "step c 2"
      - name: step c
      - run: |
          echo "step c 3"
          echo "step c 4"
          
          
