name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job-build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: Set up JDK 11
    #  uses: actions/setup-java@v3
    #  with:
    #    java-version: '11'
    #    distribution: 'adopt'
    #- name: Build with Maven
    #  run: mvn clean install        
    - name: Build with Maven
      run: echo "building ..."
  
  job-b:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: step b
        run: |
          echo "step b 1"
          echo "step b 2"

  job-c:
    
    runs-on: ubuntu-latest
    needs: [job-build-and-test, job-b]
    steps:
      - uses: actions/checkout@v3
      
      - name: step c
        run: |
          echo "step c 1"
          echo "step c 2"
          
      - uses: actions/github-script@v6
        id: my-script
        with:
          script: |
            const diff_url = "https://www.google.de/"
            const result = await github.request(diff_url)
            console.log(result)

          
          
